### ISSUE TITLE
[Wordpress 4.4] After the update some shortcodes are breaking due to extra white spaces

### ISSUE THREAD

**Issue by Robertght** [pixelgrade/pixcodes#18]
Pana acum am intalnit la Rosa pe shortcode-ul de  meniu si s-a facut un articol aici:
http://rosa-help.pixelgrade.com/support/solutions/articles/4000068906-shortcodes-problem-after-update-to-wordpress-4-4

http://help.pixelgrade.com/helpdesk/tickets/22286

Adaugati aici daca mai gasiti.

**Comment by andreilupu** [comment]
deci 4.4 sigur? nu 4.5?

**Comment by Robertght** [comment]
Sigur. :)

**Comment by Robertght** [comment]
Pentru cei care mai au probleme cu [restaurantmenu] : 
http://help.pixelgrade.com/solution/articles/4000068906-shortcodes-problem-after-update-to-wordpress-4-4

**Comment by andreilupu** [comment]
problema e din demodata
