### ISSUE TITLE
Instagram icon not displayed

### ISSUE THREAD

**Issue by raduconst** [pixelgrade/pixcodes#20]
Am testat pe Rosa si Lens sa adaug icon-ul de instagram insa nu e afisat icon-ul (nu are :before). Am atasat o imagine comparativa intre Facebook si Instagram
![insta](https://cloud.githubusercontent.com/assets/6512220/13522999/79fe4fe6-e1fb-11e5-9e2c-8dd9952f1d88.png)
L.E. Am incercat sa adaug AppNet si la fel se intampla. 

O alta problema ar fi icon-ul TripAdvisor pentru care e creat un :before insa nu e afisat:
![trip](https://cloud.githubusercontent.com/assets/6512220/13523542/c2d7fc00-e1fe-11e5-9e26-52c4a270ab1c.png)

**Comment by cristianfrumusanu** [comment]
Aici era un typo in configul de la entypo: era scris `instagrem`. N-are legatura cu pixcodes.
La fel si la Lens.
