### ISSUE TITLE
Check with the latest version of WordPress (5.1) and update headers

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/pixcodes#35]
De testat cu versiunea beta de WordPress 5.1 si rezolvat eventualele probleme. Apoi de updatat headerul "Tested up to" din readme.txt.

**Comment by BurloiuCosmin** [comment]
Readme-ul a fost updatat: https://github.com/pixelgrade/pixcodes/commit/cf96dd33d59ced9969a9907a7b8c482dfa14c600
